#!/usr/bin/python3

import numpy
import time
import sys
import datetime
sys.path.append('../../')
import py_homelab as lab

a=2
s=6
vcc=10
L="1e5"

pref="A%dS%d_L%s_%02d"%(a,s,L,vcc)

rr=(22e3, 51e3, 100e3, 220e3, 510e3, 1e6)


amin=0.1*float(L)/rr[s-1]
if amin<0.001: amin=0.001
amax=20*float(L)/rr[s-1]

freqs=[1e3]
amps=numpy.geomspace(amin, amax, 51)

lab.meas_sweep(fname=pref + "_amp.dat", amps=amps, freqs=freqs, chs='AB',
                   ext_gen=True, ext_gen_ch=0,
                   dt=1e-7, periods=100)

freqs = numpy.geomspace(1e3,4e6, 101)
amps  = (float(L)/rr[s-1],)

lab.meas_sweep(fname=pref+"_fre.dat", amps=amps, freqs=freqs, chs='AB',
                   ext_gen=True, ext_gen_ch=0,
                   dt=1e-7, periods=100)
