#!/usr/bin/python3

import matplotlib.pyplot as plt
import numpy
import os.path
import re

rnoms=(22e3, 51e3, 100e3, 220e3, 510e3, 1e6)
rnoms_l=('22k', '51k', '100k', '220k', '510k', '1M')

(f, ref) = numpy.loadtxt("data7/osc_noise.dat", unpack=1)

##################
# Label: A1S6_L1e4*
def plot_sample(ax, ddir, pref, label, noise=0):

  p1 = re.search(r'^A([0-9])S([0-9])_L([1-9e]+)', pref)
  if not p1: raise Exception("Bad prefix: " + pref)
  na = int(p1.group(1))
  ns = int(p1.group(2))
  ld = float(p1.group(3))

  # frequency-dependent load
  def ldf(R, fre):
    Cl = 5.1e-12
    Clz = 1/(1j*2*numpy.pi*fre*Cl)
    Z = numpy.abs(R*Clz/(R+Clz))
    return(Z)

  fn = "%s/A%dS%d_noise.dat"%(ddir, na,ns)
  fa = "%s/%s_amp.dat"%(ddir, pref)
  ff = "%s/%s_fre.dat"%(ddir, pref)

  # amplitude plot
  if os.path.isfile(fa):
    # plot nominal value
    xx=[1e-7,1e-2]
    ax[0][0].plot(xx, [rnoms[ns-1]]*2, 'k-', linewidth=0.5)
    (f0,v0, f1,v1,o1,r1, f2,v2,o2,r2)  = numpy.loadtxt(fa, unpack=1)
    k=v1/v2 * ldf(ld, 1e3)
    inp = v2 / ldf(ld, 1e3)
    ax[0][0].loglog(inp, k, '.-', label=label)
    # save gain (use region where output voltage <8V)
    #gains[name] = numpy.mean(k[v1<8])

  # frequency plot
  if os.path.isfile(ff):
    # plot nominal value
    xx=[1e2,1e7]
    ax[0][1].plot(xx, [rnoms[ns-1]]*2, 'k-', linewidth=0.5)
    (f0,v0, f1,v1,o1,r1, f2,v2,o2,r2)  = numpy.loadtxt(ff, unpack=1)
    k=v1/v2 * ldf(ld, f2)
    inp = v2 / ldf(ld, f2)
    ax[0][1].loglog(f2, k, '.-', label=label)

  # raw noise plot
  if noise and os.path.isfile(fn):
    (f, n) = numpy.loadtxt(fn, unpack=1)
    ax[1][0].loglog(f, 1e9*numpy.sqrt(n-ref), label=label)

  # input noise plot
  if noise and os.path.isfile(fn) and os.path.isfile(ff):
    k = numpy.interp(f, f0, k)
    ax[1][1].loglog(f, 1e12*numpy.sqrt(n-ref)/k, label=label)

#################
def set_ax(ax):
  # power supply limit
  xx=numpy.array([1e-8, 1e-2])
  ax[0][0].plot(xx, 16/xx, 'k-', linewidth=0.5, label="16/x")

  ax[0][0].set_title("gain vs input amplitude")
  ax[0][1].set_title("gain vs frequncy")
  ax[1][0].set_title("output noise")
  ax[1][1].set_title("input current noise")

  ax[0][0].set_xlabel("input current, App")
  ax[0][1].set_xlabel("freq, Hz")

  ax[0][0].set_xlim((8e-8,1e-3))
  ax[0][1].set_xlim((8e2,1e6))

  ax[1][0].set_ylim((10,1e3))
  ax[1][1].set_ylim((0.1,10))

  ax[1][0].set_ylabel("voltage noise density, nV/sqrt(Hz)")
  ax[1][1].set_ylabel("current noise density, pA/sqrt(Hz)")

  for i in (0,1):
    ax[1][i].set_xlim((10,1e6))
    ax[0][i].set_ylim((1e3,3e6))
    ax[1][i].set_xlabel("freq, Hz")
    ax[0][i].set_ylabel("Transimpedance, Ohm")

  for i in (0,1):
    for j in (0,1):
      ax[i][j].grid(which='both')
      ax[i][j].legend()

#################

ddir='data7'
for a in (1,2):
  (fig, ax) = plt.subplots(2,2, figsize=(12,8), layout='tight')
  for s in (1,2,3,4,5,6):
    pref = 'A%dS%d_L1e5'%(a,s)

    plot_sample(ax, ddir, pref, rnoms_l[s-1], noise=1)

  set_ax(ax)

  plt.savefig('plot_i2v_final%d.png'%(a))
  plt.clf()


