#!/usr/bin/python3

import matplotlib.pyplot as plt
import numpy
import os.path
import re

ddir='data6_pwr_noise'
rnoms=(22e3, 51e3, 100e3, 220e3, 510e3, 1e6)

def plot_sample(ax, ddir, pref, label):

  p1 = re.search(r'^A([0-9])S([0-9])', pref)
  if not p1: raise Exception("Bad prefix: " + pref)
  na = int(p1.group(1))
  ns = int(p1.group(2))

  fn = "%s/%s_noise.dat"%(ddir, pref)

  if os.path.isfile(fn):
    (f, n) = numpy.loadtxt(fn, unpack=1)
    ax.loglog(f, 1e9*numpy.sqrt(n), label=label)

(fig, ax) = plt.subplots(1,2, figsize=(12,8), layout='tight')

plot_sample(ax[0], ddir, 'A1S6_usb_batt', 'original')
plot_sample(ax[0], ddir, 'A1S6_usb_batt_RC_RG_G', 'best configuration')

plot_sample(ax[1], ddir, 'A1S6_hw_18v', 'original')
plot_sample(ax[1], ddir, 'A1S6_hw_18v_RC_RG_G', 'best configuration')

ax[0].set_title("9V usb batteries")
ax[1].set_title("HM310T 18V")

for i in (0,1):
  ax[i].set_ylim((10,6e4))
  ax[i].set_xlabel("freq, Hz")
  ax[i].set_ylabel("voltage noise density, nV/sqrt(Hz)")
  ax[i].grid(which='both')
  ax[i].legend()


plt.savefig('plot_i2v6_pwr_noise.png')
