#!/usr/bin/python3

import matplotlib.pyplot as plt
import numpy
import os.path

(f, ref) = numpy.loadtxt("data2/noise_osc_A_0.01.dat", unpack=1)


gains = {}
for a in (1,2):
  (fig, ax) = plt.subplots(2,2, figsize=(12,10), layout='tight')

  for s in (1,2,3,4,5,6):
    name = "A%dS%d"%(a,s)
    fn = "data2/noise_%s_A_0.01.dat"%(name)
    ff = "data/%s_fre.dat"%(name)
    fa = "data/%s_amp.dat"%(name)

    # amplitude plot
    if os.path.isfile(fa):
      (f0,v0, f1,v1,o1,r1, f2,v2,o2,r2)  = numpy.loadtxt(fa, unpack=1)
      k=v1/v2
      ax[0][0].loglog(v2, k, '.-', label="S%d"%(s))
      # save gain (use region where output voltage <8V)
      gains[name] = numpy.mean(k[v1<8])

    # frequency plot
    if os.path.isfile(ff):
      (f0,v0, f1,v1,o1,r1, f2,v2,o2,r2)  = numpy.loadtxt(ff, unpack=1)
      k=v1/v2
      ax[0][1].loglog(f0, k, '.-', label="S%d"%(s))

    # raw noise plot
    if os.path.isfile(fn):
      (f, n) = numpy.loadtxt(fn, unpack=1)
      ax[1][0].loglog(f, 1e9*numpy.sqrt(n-ref), label="S%d"%(s))

    # input noise plot
    if os.path.isfile(fn) and os.path.isfile(ff):
      k = numpy.interp(f, f0, k)
      ax[1][1].loglog(f, 1e9*numpy.sqrt(n-ref)/k, label="S%d"%(s))


  ax[1][0].loglog(f, 1e9*numpy.sqrt(ref), label="Picoscope")

  ax[0][0].set_title("gain vs input amplitude")
  ax[0][1].set_title("gain vs frequncy")
  ax[1][0].set_title("output noise")
  ax[1][1].set_title("input noise")

  ax[0][0].set_xlabel("amp, Vpp")
  ax[0][1].set_xlabel("freq, Hz")
  xx=numpy.array([1e-3, 1e2])
  ax[0][0].plot(xx, 16/xx, 'k-', linewidth=0.5, label="16/x")
  ax[0][0].set_ylim((0.1,1e3))
  ax[0][1].set_ylim((0.1,1e3))


  ax[1][0].set_ylim((1,1e4))
  ax[1][1].set_ylim((3,1e3))

  for i in (0,1):
    ax[1][i].set_xlim((10,1e6))
    ax[1][i].set_xlabel("freq, Hz")
    ax[1][i].set_ylabel("voltage noise density, nV/sqrt(Hz)")
    ax[0][i].set_ylabel("gain")

  for i in (0,1):
    for j in (0,1):
      ax[i][j].grid(which='both')
      ax[i][j].legend()

  plt.savefig('plot_amps_ch%s.png'%(a))

plt.clf()

# save gains to file and make plot
fo = open("gains.dat", "w")
print("# switch res  gain1 gain2", file=fo)
res = (1e9, 10000, 3300, 1000, 330, 100) # gain resistors
for s in (1,2,3,4,5,6):
  n1 = "A1S%d"%(s)
  n2 = "A2S%d"%(s)
  if n1 in gains: g1 = gains[n1]
  else: g1=0
  if n2 in gains: g2 = gains[n2]
  else: g2=0
  print("%d %5.0f  %6.4f %6.4f"%(s, res[s-1], g1, g2), file=fo)
fo.close()

(fig, ax) = plt.subplots(1,1, figsize=(8,6), layout='tight')
(ss, rr, g1,g2) = numpy.loadtxt("gains.dat", unpack=1)
xx=numpy.geomspace(50, 1e6, 101)
ax.loglog(xx, 1+50e3/xx, "k-", label="1 + 50k/x")
ax.loglog(rr, g1, "b*", label="channel 1")
ax.loglog(rr, g2, "r*", label="channel 2")
ax.legend()
ax.grid(which='both')
ax.set_xlim((50,1e5))
ax.set_ylim((1,1e3))
ax.set_xlabel("Gain resistor, Ohm")
plt.savefig('plot_amps_gain.png')
