#!/usr/bin/python3

import numpy
import time
import sys
import re
import datetime
sys.path.append('../../')
import py_homelab as lab

RR=1e6
RL=1e5

pref="C1_R%.0e_L%.0e"%(RR,RL)
k=RR/RL # R/L
pref=re.sub(r'e\+0', 'e', pref)

amin=0.001
amax=18

freqs=[1e3]
amps=numpy.geomspace(amin, amax, 51)

lab.meas_sweep(fname="%s_amp.dat"%(pref), amps=amps, freqs=freqs, chs='AB',
                   ext_gen=True, ext_gen_ch=0,
                   dt=1e-7, periods=100)

freqs = numpy.geomspace(1e3,4e6, 101)
if k<1: amps=(0.1*k,)
else: amps=(0.1,)

lab.meas_sweep(fname="%s_fre.dat"%(pref), amps=amps, freqs=freqs, chs='AB',
                   ext_gen=True, ext_gen_ch=0,
                   dt=1e-7, periods=100)
